name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  fast-ci:
    uses: Ali-5873/.github/.github/workflows/fast-ci.yml@main
    with:
      language: node
      node-version: "20"