name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  quality-gate:
    name: central-quality-gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run central quality gate
        uses: Ali-5873/.github/actions/quality-gate@main
        with:
          language: node