name: Release Docker Image

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  docker-release:
    uses: Ali-5873/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: demo-node-app
      dockerfile: Dockerfile
      context: .